### ISSUE TITLE
Dream plug-in - Does it work for 49.2?

### ISSUE THREAD

**Issue by elegantscience** [stackdevelopment/sketch-pixel-cleanup#3]
Maybe I'm doing something wrong, but it's possible that 49.2 or an earlier version of Sketch may have caused issues. I installed the plug-in, and have selected a previously created rectangle that annoying has a border measuring 2.5 pixels. I have selected it both as a single layer and as a group and run the plug-in with no result.

Am I doing something wrong?

**Comment by elegantscience** [comment]
Ignore the previous post. Figured it out. By the way... thanks. This saves a ton of time.

**Comment by averydev** [comment]
Great!
