### ISSUE TITLE
X and Y positioning clean up no longer works

### ISSUE THREAD

**Issue by marinovbiz** [stackdevelopment/sketch-pixel-cleanup#5]
The X and Y positioning cleanup no longer works. I'm currently running  Version 69.2 (107504)

**Comment by randavictor** [comment]
same for me - not working!

**Comment by davelowensohn** [comment]
Thanks for your feedback – this repository is unfortunately no longer supported. Please feel free to fork and update if it isn't working with your version of Sketch.
